## Chap 1

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
m = np.array([[1, 5, 2],
[4, 7, 4],
[2, 0, 9]])

In [6]:
print(m)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [7]:
m.shape

(3, 3)

In [10]:
m.transpose()

array([[1, 4, 2],
       [5, 7, 0],
       [2, 4, 9]])

In [11]:
x = np.array([1, 2, 3, 4, 5])

In [12]:
x.transpose()

array([1, 2, 3, 4, 5])

In [13]:
print ('Matrix Determinant:', np.linalg.det(m), '\n')

Matrix Determinant: -105.00000000000006 



In [14]:
m_inv = np.linalg.inv(m)
print ('Matrix inverse:\n', m_inv, '\n')

Matrix inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 



In [18]:
names = ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hannah", 
         "Ian", "Jack", "Katie", "Leo", "Mia", "Nina", "Oscar", "Paul", 
         "Quinn", "Rachel", "Sam", "Tina", "Uma", "Violet", "Will", 
         "Xander", "Yara", "Zane", "Charlie", "David", "Eva", "Frank", "Grace", "Hannah", 
         "Ian", "Jack", "Katie", "Leo", "Mia", "Nina", "Oscar", "Paul", 
         "Quinn", "Rachel", "Sam", "Tina", "Uma", "Violet", "Will", 
         "Xander", "Yara", "Zane"]

In [20]:
grade = np.random.choice(["A", "B", "C", "D", "F"], 50)

In [22]:
obedient = np.random.choice(["Y", "N"], 50)

In [24]:
researchScore = np.random.randint(50, 100, 50)

In [26]:
projectScore = np.random.randint(50, 100, 50)

In [27]:
recommend = np.random.choice(["Y", "N"], 50)

In [28]:
df = pd.DataFrame({"Name": names, "overallGrade": grade, "Obedient":obedient, "ResearchScore": researchScore, "ProjectScore": projectScore, "Recommend": recommend })

In [32]:
df.columns

Index(['Name', 'overallGrade', 'Obedient', 'ResearchScore', 'ProjectScore',
       'Recommend'],
      dtype='object')

In [33]:
X = df[['overallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']]
y = df[["Recommend"]]

We will now use a standard scalar from scikit-learn to scale or normalize our two numeric scorebased
attributes using the following code.

In [36]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X[['ResearchScore', 'ProjectScore']])
X[['ResearchScore', 'ProjectScore']] = ss.transform( X[['ResearchScore', 'ProjectScore']])

/tmp/ipykernel_4005/50201671.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['ResearchScore', 'ProjectScore']] = ss.transform( X[['ResearchScore', 'ProjectScore']])


In [38]:
X = pd.get_dummies(X, columns=['overallGrade', 'Obedient'])

In [39]:
X

ResearchScore  ProjectScore  overallGrade_A  overallGrade_B  \
0       -0.421134      0.655070           False           False   
1        0.939674     -0.800641           False           False   
2       -0.277891     -0.218357           False           False   
3       -0.922485     -1.601282           False            True   
4       -1.065728     -0.291142           False           False   
5        0.939674      0.800641            True           False   
6        0.223459     -0.582284           False           False   
7       -0.277891      0.436713           False           False   
8        0.366702     -0.655070           False            True   
9        0.438323      0.291142           False            True   
10      -1.280592     -1.819638           False           False   
11      -1.208971      1.164568           False            True   
12      -0.850863     -1.674067           False           False   
13      -0.850863      0.727855            True           False   
14       0.939674     -1.237354            True           False   
15      -1.352214      0.800641           False           False   
16      -0.063027     -0.582284           False           False   
17      -1.352214     -0.145571           False           False   
18       0.151838     -0.873426           False           False   
19       1.154538      1.164568           False           False   
20      -0.564377      1.237354           False            True   
21      -0.994106      1.455710           False           False   
22       0.223459      0.727855           False           False   
23      -0.994106      1.164568           False           False   
24      -0.564377     -1.892424           False            True   
25      -0.421134      0.072786           False           False   
26       1.226160      1.528496           False           False   
27       1.870753     -0.655070           False            True   
28      -1.065728      1.455710           False            True   
29       0.581566      0.582284           False           False   
30      -1.423835     -0.727855           False           False   
31      -0.206270      1.674067           False           False   
32       0.080216      0.800641           False           False   
33       0.151838      0.291142           False           False   
34      -0.707620      0.873426           False            True   
35       1.870753     -0.582284           False            True   
36       0.796431      0.291142           False            True   
37       1.727510      0.800641           False           False   
38       1.727510     -1.382925           False           False   
39      -0.564377      1.164568           False           False   
40      -1.423835     -1.382925           False           False   
41       0.724809     -1.091783           False           False   
42       1.584267      0.582284           False           False   
43       1.942374     -0.363928           False            True   
44       0.008595     -0.291142           False           False   
45       0.939674     -0.582284           False           False   
46       0.438323     -0.873426           False           False   
47      -1.352214      0.800641           False           False   
48      -0.994106     -1.674067           False           False   
49       0.151838      0.436713            True           False   

    overallGrade_C  overallGrade_D  overallGrade_F  Obedient_N  Obedient_Y  
0             True           False           False        True       False  
1            False            True           False       False        True  
2             True           False           False       False        True  
3            False           False           False        True       False  
4            False            True           False       False        True  
5            False           False           False       False        True  
6            False            True           Fa

### Modeling

In [40]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X, y)

/home/justin/.pyenv/versions/3.11.7/lib/python3.11/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

### Model Evaluation

In [41]:
yhat = logreg.predict(X)

In [42]:
yhat

array(['N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y',
       'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y',
       'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N'],
      dtype=object)

In [43]:
y

Recommend
0          N
1          N
2          N
3          N
4          Y
5          Y
6          Y
7          N
8          Y
9          N
10         Y
11         N
12         Y
13         Y
14         N
15         N
16         Y
17         Y
18         N
19         Y
20         N
21         N
22         Y
23         N
24         N
25         N
26         Y
27         N
28         N
29         N
30         Y
31         Y
32         N
33         Y
34         Y
35         N
36         N
37         N
38         Y
39         N
40         Y
41         Y
42         Y
43         N
44         Y
45         N
46         Y
47         Y
48         Y
49         N

In [44]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [45]:
accuracy_score(y, yhat)

0.72

In [46]:
classification_report(y, yhat)

'              precision    recall  f1-score   support\n\n           N       0.73      0.73      0.73        26\n           Y       0.71      0.71      0.71        24\n\n    accuracy                           0.72        50\n   macro avg       0.72      0.72      0.72        50\nweighted avg       0.72      0.72      0.72        50\n'