## Numpy

In [1]:
import numpy as np

### Linear Algebra Using numpy

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[1,2,3]])

In [4]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
B

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [3]:
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [6]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Pandas

In [8]:
import pandas as pd

In [14]:
df = pd.read_csv("worldcities.csv")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47868 entries, 0 to 47867
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   city        47868 non-null  object 
 1   city_ascii  47867 non-null  object 
 2   lat         47868 non-null  float64
 3   lng         47868 non-null  float64
 4   country     47868 non-null  object 
 5   iso2        47835 non-null  object 
 6   iso3        47868 non-null  object 
 7   admin_name  47671 non-null  object 
 8   capital     13023 non-null  object 
 9   population  47656 non-null  float64
 10  id          47868 non-null  int64  
dtypes: float64(3), int64(1), object(7)
memory usage: 4.0+ MB


In [17]:
df

city        city_ascii      lat       lng  \
0                 Tokyo             Tokyo  35.6897  139.6922   
1               Jakarta           Jakarta  -6.1750  106.8275   
2                 Delhi             Delhi  28.6100   77.2300   
3             Guangzhou         Guangzhou  23.1300  113.2600   
4                Mumbai            Mumbai  19.0761   72.8775   
...                 ...               ...      ...       ...   
47863        Munha-dong        Munha-dong  39.3813  127.2517   
47864            Sil-li            Sil-li  39.4880  125.4640   
47865              Muan              Muan  34.9897  126.4714   
47866         Hongseong         Hongseong  36.6009  126.6650   
47867  Charlotte Amalie  Charlotte Amalie  18.3420  -64.9331   

                   country iso2 iso3      admin_name  capital  population  \
0                    Japan   JP  JPN           Tōkyō  primary  37732000.0   
1                Indonesia   ID  IDN         Jakarta  primary  33756000.0   
2                    India   IN  IND           Delhi    admin  32226000.0   
3                    China   CN  CHN       Guangdong    admin  26940000.0   
4                    India   IN  IND     Mahārāshtra    admin  24973000.0   
...                    ...  ...  ...             ...      ...         ...   
47863         Korea, North   KP  PRK         Kangwŏn      NaN         NaN   
47864         Korea, North   KP  PRK       P’yŏngnam      NaN         NaN   
47865         Korea, South   KR  KOR         Jeonnam    admin         NaN   
47866         Korea, South   KR  KOR        Chungnam    admin         NaN   
47867  U.S. Virgin Islands   VI  VIR  Virgin Islands  primary         NaN   

               id  
0      1392685764  
1      1360771077  
2      1356872604  
3      1156237133  
4      1356226629  
...           ...  
47863  1408979215  
47864  1408767958  
47865  1410001061  
47866  1410822139  
47867  1850037473  

[47868 rows x 11 columns]

In [18]:
df.iloc[:5, :4]

city city_ascii      lat       lng
0      Tokyo      Tokyo  35.6897  139.6922
1    Jakarta    Jakarta  -6.1750  106.8275
2      Delhi      Delhi  28.6100   77.2300
3  Guangzhou  Guangzhou  23.1300  113.2600
4     Mumbai     Mumbai  19.0761   72.8775

In [22]:
df[df["city"] == "Dallas"]

city city_ascii      lat       lng        country iso2 iso3  \
94     Dallas     Dallas  32.7935  -96.7667  United States   US  USA   
28084  Dallas     Dallas  44.9221 -123.3130  United States   US  USA   
32158  Dallas     Dallas  33.9152  -84.8416  United States   US  USA   
44268  Dallas     Dallas  41.3608  -75.9656  United States   US  USA   

         admin_name capital  population          id  
94            Texas     NaN   5830932.0  1840019440  
28084        Oregon     NaN     16945.0  1840018590  
32158       Georgia     NaN     14126.0  1840014757  
44268  Pennsylvania     NaN      9108.0  1840000745

In [36]:
df_us = df[df['iso3'] == "USA" ]
df_us_above_10m = df_us[df_us['population'] > 5000000]
df_us_above_10m

city    city_ascii      lat       lng        country iso2 iso3  \
11       New York      New York  40.6943  -73.9249  United States   US  USA   
33    Los Angeles   Los Angeles  34.1141 -118.4068  United States   US  USA   
55        Chicago       Chicago  41.8375  -87.6866  United States   US  USA   
88          Miami         Miami  25.7840  -80.2101  United States   US  USA   
90        Houston       Houston  29.7860  -95.3885  United States   US  USA   
94         Dallas        Dallas  32.7935  -96.7667  United States   US  USA   
100  Philadelphia  Philadelphia  40.0077  -75.1339  United States   US  USA   
122       Atlanta       Atlanta  33.7628  -84.4220  United States   US  USA   
123    Washington    Washington  38.9047  -77.0163  United States   US  USA   

               admin_name  capital  population          id  
11               New York      NaN  18908608.0  1840034016  
33             California      NaN  11922389.0  1840020491  
55               Illinois      NaN   8497759.0  1840000494  
88                Florida      NaN   6080145.0  1840015149  
90                  Texas      NaN   5970127.0  1840020925  
94                  Texas      NaN   5830932.0  1840019440  
100          Pennsylvania      NaN   5683533.0  1840000673  
122               Georgia    admin   5180179.0  1840013660  
123  District of Columbia  primary   5116378.0  1840006060